const KARATS=[8,14,18,20,22,24];
const defaults={max:86,pawn1:55,pawn2:75,offers:[12,29,49,75]};
let config=JSON.parse(localStorage.getItem('goldConfig')||'null')||defaults;
const state={weights:Object.fromEntries(KARATS.map(k=>[k,0])),price:75};
const €=v=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(v||0);
const n=v=>Number.parseFloat(String(v).replace(',','.'))||0;
function renderInputs(){document.querySelector('#karatInputs').innerHTML=KARATS.map(k=>`<div class="karat-card"><label>${k}K</label><input data-karat="${k}" type="number" min="0" step="0.01" inputmode="decimal" placeholder="0,00"><em>gramos</em></div>`).join('');document.querySelectorAll('[data-karat]').forEach(i=>i.addEventListener('input',e=>{state.weights[e.target.dataset.karat]=n(e.target.value);calculate()}))}
function calculate(){const total=Object.values(state.weights).reduce((a,b)=>a+b,0);const eq=KARATS.reduce((a,k)=>a+state.weights[k]*(k/18),0);const fine=KARATS.reduce((a,k)=>a+state.weights[k]*(k/24),0);const purity=total?fine/total*100:0;document.querySelector('#totalWeight').textContent=`${total.toFixed(2)} g · equivalente 18K: ${eq.toFixed(2)} g`;document.querySelector('#totalValue').textContent=€(eq*state.price);document.querySelector('#grossValue').textContent=€(eq*state.price);document.querySelector('#eq18').textContent=`${eq.toFixed(2)} g`;document.querySelector('#purity').textContent=`${purity.toFixed(1)}%`;document.querySelector('#buyWeight').textContent=`${eq.toFixed(2)} g`;renderOffers(eq);renderPawns(eq)}
function renderOffers(eq){const offers=[...config.offers,config.max].sort((a,b)=>a-b);document.querySelector('#offerTable').innerHTML=offers.map((r,i)=>`<div class="offer"><div><span>${r===config.max?'Máximo':'Oferta '+(i+1)}</span><div class="rate">${r.toFixed(2)} €/g</div></div><div class="amount">${€(eq*r)}</div></div>`).join('');document.querySelector('#maxOffer').textContent=`${config.max.toFixed(2)} €/g`}
function renderPawns(eq){const vals=[config.pawn1,config.pawn2];document.querySelector('#pawnTable').innerHTML=vals.map((r,i)=>`<div class="offer"><div><span>${i?'Garantía alta':'Garantía básica'}</span><div class="rate">${r.toFixed(2)} €/g</div></div><div class="amount">${€(eq*r)}</div></div>`).join('');document.querySelector('#pawnRecommended').textContent=€(eq*config.pawn2)}
function loadConfig(){[['cfgMax','max'],['cfgPawn1','pawn1'],['cfgPawn2','pawn2']].forEach(([id,k])=>document.getElementById(id).value=config[k]);config.offers.forEach((v,i)=>document.getElementById(`cfgOffer${i+1}`).value=v)}
function saveHistory(){const total=Object.values(state.weights).reduce((a,b)=>a+b,0);if(!total)return;const eq=KARATS.reduce((a,k)=>a+state.weights[k]*(k/18),0);const items=JSON.parse(localStorage.getItem('goldHistory')||'[]');items.unshift({date:new Date().toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'}),weight:total,eq,value:eq*state.price});localStorage.setItem('goldHistory',JSON.stringify(items.slice(0,20)));renderHistory()}
function renderHistory(){const list=document.getElementById('historyList');const items=JSON.parse(localStorage.getItem('goldHistory')||'[]');list.innerHTML=items.map(x=>`<div class="history-item"><strong>${€(x.value)}</strong><div>${x.weight.toFixed(2)} g · ${x.eq.toFixed(2)} g eq. 18K</div><small>${x.date}</small></div>`).join('')}
function clearAll(){document.querySelectorAll('[data-karat]').forEach(i=>i.value='');KARATS.forEach(k=>state.weights[k]=0);calculate()}
document.getElementById('priceRange').addEventListener('input',e=>{state.price=n(e.target.value);document.getElementById('referencePrice').textContent=`${state.price.toFixed(2)} €/g`;calculate()});
document.getElementById('clearBtn').addEventListener('click',clearAll);
document.getElementById('saveConfig').addEventListener('click',()=>{config={max:n(cfgMax.value)||defaults.max,pawn1:n(cfgPawn1.value)||defaults.pawn1,pawn2:n(cfgPawn2.value)||defaults.pawn2,offers:[1,2,3,4].map(i=>n(document.getElementById(`cfgOffer${i}`).value)).map((v,i)=>v||defaults.offers[i])};localStorage.setItem('goldConfig',JSON.stringify(config));calculate();alert('Configuración guardada')});
document.querySelectorAll('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.view).classList.add('active');if(btn.dataset.view==='historial')renderHistory()}));
document.getElementById('themeBtn').addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('goldTheme',document.body.classList.contains('light')?'light':'dark')});
if(localStorage.getItem('goldTheme')==='light')document.body.classList.add('light');
renderInputs();loadConfig();renderHistory();calculate();